### ISSUE TITLE
我还是没明白怎么使用

### ISSUE THREAD

**Issue by hsl9999** [keepyounger/CornerstoneCrack#1]
我下好官方的，改名成conerstone4了。然后也下了这个工程，我是直接把 Cornerstone.app 这个目录COPY到Application下，跟官方的目录一样吗？

**Comment by hsl9999** [comment]
我知道了，安装完后是 用 conerstone 2 那个运行吧？我的版本是 10.12，你这个要 10.13，系统要升级

**Comment by keepyounger** [comment]
第一个问题：只要保证官方的在/Application下面名称为Cornerstone4就可以了，这个工程的放哪儿都行，无所谓，关于第二个问题你可以修改info.plist的LSMinimumSystemVersion为10.12试试

**Comment by hsl9999** [comment]
我升级了系统 10.13.5 ，运行发现 cornerstone 2 不能打开。

**Comment by keepyounger** [comment]
Cornerstone4 注意区分大小写

**Comment by hsl9999** [comment]
名字大小写没错，看了下。

**Comment by hsl9999** [comment]
没办法截图。

应用程序“Cornerstone2”不能打开

Cornerstone2
Cornerstone4

后面两个是应用程序名字。

**Comment by keepyounger** [comment]
看不到你怎么操作的。。。

**Comment by hsl9999** [comment]
有QQ吗，帮我远程操作下。加我 894159476

**Comment by keepyounger** [comment]
发你QQ邮箱了

**Comment by keepyounger** [comment]
允许任何来源了吗？
![image](https://user-images.githubusercontent.com/6264752/41091059-472abe76-6a78-11e8-9450-245f2bdb253b.png)

**Comment by hsl9999** [comment]
允许了，这是OK的。

**Comment by hsl9999** [comment]
不然我的很多MAC软件装不了，：）

**Comment by hsl9999** [comment]
下了你的最新版本，解压后是 Cornerstone 3，我把它复制到 Application 下面，双击打不开，没提示。

**Comment by keepyounger** [comment]
你这个很奇怪 我觉得应该是什么权限问题 暂时没有解决方案 你可以自己编译源代码  有教程  下面是脚本内容 根据目录自己修改下
```
#!/bin/sh
CurrentAppPath=$(cd $(dirname $0) && pwd)
DYLD_INSERT_LIBRARIES=${CurrentAppPath}/libCornerstoneCrack.dylib ${CurrentAppPath}/Cornerstone4.app/Contents/MacOS/Cornerstone
```
